# Generated by Django 2.2.12 on 2020-07-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
