# Generated by Django 2.2.12 on 2020-05-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_id',
            field=models.CharField(default='6g3Yzt77oUE', max_length=11),
        ),
    ]
