# Generated by Django 2.2.12 on 2020-05-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_id',
            field=models.CharField(max_length=11),
        ),
    ]
