# Generated by Django 2.2.12 on 2020-07-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_project_github_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video_id',
        ),
    ]
